### PR TITLE
Updated to 1.18.30

### PR DESCRIPTION
**Pull request by ProtectorYT364**

### CODE REVIEW

**Comment by VaxPex** [comment]
https://github.com/Benedikt05/BetterAltay
https://github.com/MCPE357/EskoBE.git

**Comment by ProtectorYT364** [comment]
lul

**Comment by VaxPex** [comment]
the creators of this bullshit is gays

**Comment by VaxPex** [comment]
+ gays and gays

**Comment by VaxPex** [comment]
+ dumbs

**Comment by VaxPex** [comment]
+ donkeys

**Comment by VaxPex** [comment]
the contributors are trash

**Comment by VaxPex** [comment]
And gays

**Comment by VaxPex** [comment]
+ mfs

**Comment by VaxPex** [comment]
+ dumbs

**Comment by VaxPex** [comment]
+ GAYSS

**Comment by VaxPex** [comment]
kids

**Comment by VaxPex** [comment]
deleting my comments

**Comment by krishna344d** [comment]
Bro,pls release it.

**Pull request closed without merging**
