### PR TITLE
Protocol Updates

### PR DESCRIPTION
**Pull request by ItsToxicGG**
protocols updates (excluding multiversion kinda as shown in this pull request protocol info has new things)

### CODE REVIEW

**Comment by ItsToxicGG** [comment]
also mabye multiversion idk \

**Comment by ItsToxicGG** [comment]
i forgot about some files but now done

**Comment by ItsRealNise** [comment]
we can't update to multiversion or protocol, because can take bug with the any plugins

**Comment by ItsToxicGG** [comment]
fr

**Comment by ItsToxicGG** [comment]
> we can't update to multiversion or protocol, because can take bug with the any plugins
really not in my case

**Pull request closed without merging**
